language: cpp

os:
  - linux
  - osx

env:
  global:
    - MAKEFLAGS="-j 2"

osx_image: xcode11

sudo: false
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-regex-dev
      - libeigen3-dev
      - libflann-dev
      - libgomp1
      - libtinyxml2-dev

compiler:
  - clang
  - gcc

# Let us install a set of Homebrew packages for Mac OS X. This appears
# to be rather clunky, but the official documentation contains similar
# examples.
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install eigen     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pybind11  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install rapidjson ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install tinyxml2  ; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - CTEST_OUTPUT_ON_FAILURE=1 make test
